[package]
name = "rust-ws-server"
version = "0.1.0"
authors = [""]

[dependencies]
clap = "2.11"
mioco = "0.8"
num_cpus = "1.0"
scoped-pool = "1.0"
serde = "0.8"
serde_json = "0.8"
threadpool = "1.0"
ws = "0.5.1"
